version: '2'

services:
  iota_zmq_sub:
    build:
      context: .
    command: [ "node", "./src/zmq.js" ]
    volumes:
      - ./storage:/app/storage
    environment:
      - ZMQ_HOST=tcp://localhost:5556
      - IRI_HOST=http://localhost:14265
  iota_promoter:
      build:
        context: .
      command: [ "node", "./src/promoter.js" ]
      volumes:
        - ./storage:/app/storage
      environment:
        - ZMQ_HOST=tcp://localhost:5556
        - IRI_HOST=http://localhost:14265
